//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace String_Splitter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("String_Splitter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bob
        ///has
        ///the
        ///be
        ///and
        ///of
        ///a
        ///in
        ///to
        ///have
        ///to
        ///it
        ///I
        ///that
        ///for
        ///you
        ///he
        ///with
        ///on
        ///do
        ///say
        ///this
        ///they
        ///at
        ///but
        ///we
        ///his
        ///from
        ///that
        ///not
        ///n&apos;t
        ///n&apos;t
        ///by
        ///she
        ///or
        ///as
        ///what
        ///go
        ///their
        ///can
        ///who
        ///get
        ///if
        ///would
        ///her
        ///all
        ///my
        ///make
        ///about
        ///know
        ///will
        ///as
        ///up
        ///one
        ///time
        ///there
        ///year
        ///so
        ///think
        ///when
        ///which
        ///them
        ///some
        ///me
        ///people
        ///take
        ///out
        ///into
        ///just
        ///see
        ///him
        ///your
        ///come
        ///could
        ///now
        ///than
        ///like
        ///other
        ///how
        ///then
        ///its
        ///our
        ///two
        ///more
        ///these
        ///want
        ///way
        ///look
        ///first
        ///also
        ///new
        ///because
        ///day
        ///more
        ///use
        ///no
        ///ma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dictionary {
            get {
                return ResourceManager.GetString("Dictionary", resourceCulture);
            }
        }
    }
}
